name    'crayfishx-gemsource'
version '0.1.1'
source 'http://github.com/crayfishx/puppet-gemsource'
author 'crayfishx'
license 'Apache License, Version 2.0'
summary 'Manage gem sources'
description 'Manages gem sources with support for PE inbuilt rubygems'
project_page 'http://github.com/crayfishx/puppet-gemsource'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
